if __name__ == '__main__':
    from oop.sports import *
    arena = Arena()
    player1 = Player("Jan Kowalski", 1200)
    player2 = Player("Jan Nowak", 1200)
    player3 = Player("Jan Lewandowski", 1200)
    game1 = Game(player1, player2, 1)
    game2 = Game(player1, player3, 2)
    game3 = Game(player2, player3, 2)
    arena.add(game1)
    arena.add(game2)
    arena.add(game3)
    arena.stats()
    print(arena.standings[0])
    print(arena.standings[1])
    print(arena.standings[2])
